_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/home/zhangql/ResTV2/workdirs/restv2_base_224.pth"
  PIXEL_MEAN: [ 123.675, 116.28, 103.53 ]
  PIXEL_STD: [ 58.395, 57.12, 57.375 ]
  MASK_ON: True
  BACKBONE:
    NAME: "build_restv2_fpn_backbone"
  RESTV2:
    NAME: "restv2_base"
    OUT_FEATURES: [ "stage1", "stage2", "stage3", "stage4" ]
  FPN:
    IN_FEATURES: [ "stage1", "stage2", "stage3", "stage4" ]
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (480, 512, 534, 576, 640, 672, 704, 736, 768, 800)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  WEIGHT_DECAY: 0.05
  BASE_LR: 0.0001
  AMP:
    ENABLED: True
TEST:
  EVAL_PERIOD: 20000

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
