_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: ""
  BACKBONE:
    NAME: "build_rest_fpn_backbone"
  MASK_ON: True
  REST:
    NAME : "rest_base"
    OUT_FEATURES: ["stage1", "stage2", "stage3", "stage4"]
  FPN:
    IN_FEATURES: ["stage1", "stage2", "stage3", "stage4"]
SOLVER:
  OPTIMIZER: "AdamW"
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.05
OUTPUT_DIR: "output/mask_rcnn/rest_base_ms_1x"
